### PR TITLE
adding css file

### PR DESCRIPTION
**Pull request by shalinidc**

### CODE REVIEW

**Comment by shalinidc** [comment]
I might have done something wrong here.

**Comment by rajpranz** [comment]
You need to add a close or closing comment with your issue number

**Comment by TheCandiko** [comment]
I thought that I wrote an answer for it. I think I've started it and I didn't finish it. Sorry.

This Pull Request #9 should be connected with the issue #8 in order to move related card in Waffle.
To make the connection with the PR and the issue we have two ways:
  1. We can use closing keywords to close the issue. If the PR approved and merged, it will close the issue. But it won't move cards automatically in Waffle.
  2. We can put the related issue number into name of the branch like `type-branchName-#8`. If you push the branch to remote, Waffle will assign the issue to you when it sees the issue number in the branch name `feature-testForWaffle-#8`. After this if you open PR from this branch, Waffle will automatically connect the issue and PR. It will move the issue card to Review in Waffle. When we close it, we simply will use closing keywords. If PR is approved and merged, then issue will close automatically and related card in Waffle will be moved to Done automatically.

The problem here is when @shalinidc gave the branch name, she used the #6 and tried to connect it with Issue No. #6 . It is because I misguided you in the exercise :laughing: 

Solution will be create a new branch name with mentioning the right issue #8 , push it and make the changes afterwards. Please check the assignment and card moving is completed in Waffle. Then, you can made the necessary changes and can open a pull request.

I'm now closing this PR and move the card #8 to Inbox in Waffle.

**Comment by shalinidc** [comment]
Thank you for the detailed explanation @DarisCalinor, it helps a lot.:) I am going to retrace my steps again.

**Pull request closed without merging**
